import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as path;
import 'package:yaml/yaml.dart';

const generatedDependenciesStart = '# BEGIN GENERATED THEME DEPENDENCIES';
const generatedDependenciesEnd = '# END GENERATED THEME DEPENDENCIES';

const _themePackagePrefix = 'theme_';

class ThemePackage {
  const ThemePackage({
    required this.packageName,
    required this.themeName,
    required this.builderName,
    required this.directory,
  });

  final String packageName;
  final String themeName;
  final String builderName;
  final Directory directory;
}

ThemePackage getThemePackage(Directory projectDirectory) {
  final directory = Directory(projectDirectory.resolveSymbolicLinksSync());
  final manifest = File(_join(directory.path, 'pubspec.yaml'));
  final pubspec = loadYaml(manifest.readAsStringSync());
  final packageName = pubspec is YamlMap ? pubspec['name'] : null;
  if (packageName is! String || !packageName.startsWith(_themePackagePrefix)) {
    throw FormatException('Theme package names must start with theme_.');
  }
  final themeName = packageName.substring(_themePackagePrefix.length);
  if (!RegExp(r'^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$').hasMatch(themeName)) {
    throw FormatException(
      'Theme package $packageName must use a lowercase underscore name.',
    );
  }
  final libDirectory = Directory(_join(directory.path, 'lib'));
  final entrypoint = File(_join(libDirectory.path, 'theme.dart'));
  final sceneFiles = libDirectory.existsSync()
      ? libDirectory
            .listSync(recursive: true, followLinks: false)
            .whereType<File>()
            .where((file) => file.path.endsWith('.scene.json'))
            .toList()
      : const <File>[];
  if (!entrypoint.existsSync() || sceneFiles.isEmpty) {
    throw FormatException(
      '$packageName must contain lib/theme.dart and a .scene.json document.',
    );
  }
  final builderName = _builderName(themeName);
  if (!RegExp(r'\b' + RegExp.escape(builderName) + r'\s*\(')
      .hasMatch(entrypoint.readAsStringSync())) {
    throw FormatException(
      '$packageName must export $builderName() from lib/theme.dart.',
    );
  }
  return ThemePackage(
    packageName: packageName,
    themeName: themeName,
    builderName: builderName,
    directory: directory,
  );
}

List<ThemePackage> findThemePackages(Directory repoRoot) {
  final themesDirectory = Directory(_join(repoRoot.path, 'themes'));
  final themes = themesDirectory
      .listSync(followLinks: false)
      .whereType<Directory>()
      .where(
        (directory) => File(_join(directory.path, 'pubspec.yaml')).existsSync(),
      )
      .map(getThemePackage)
      .toList();
  themes.sort((left, right) => left.packageName.compareTo(right.packageName));
  final names = <String>{};
  for (final theme in themes) {
    if (!names.add(theme.themeName)) {
      throw StateError('Duplicate theme name: ${theme.themeName}');
    }
  }
  for (final requiredName in ['default', 'fallback']) {
    if (!names.contains(requiredName)) {
      throw StateError('The theme catalog requires theme_$requiredName.');
    }
  }
  return themes;
}

void writeThemeCatalog({
  required Directory repoRoot,
  required List<ThemePackage> themes,
}) {
  final catalogDirectory = Directory(
    _join(repoRoot.path, 'packages/theme_catalog'),
  );
  final pubspec = File(_join(catalogDirectory.path, 'pubspec.yaml'));
  if (!pubspec.existsSync()) {
    throw StateError('Missing theme catalog pubspec: ${pubspec.path}');
  }
  pubspec.writeAsStringSync(
    _withGeneratedDependencies(
      pubspec.readAsStringSync(),
      themes,
      catalogDirectory,
    ),
  );

  final registry = File(
    _join(catalogDirectory.path, 'lib/src/theme_registry.g.dart'),
  );
  registry.writeAsStringSync(generateThemeRegistry(themes));
}

String generateThemeRegistry(List<ThemePackage> themes) {
  final imports = StringBuffer()
    ..writeln("import 'package:flutter/material.dart';")
    ..writeln("import 'package:theme_sdk/theme_sdk.dart';");
  for (final theme in themes) {
    imports.writeln(
      "import 'package:${theme.packageName}/theme.dart' show ${theme.builderName};",
    );
  }

  final builders = themes
      .map(
        (theme) =>
            "    '${theme.themeName}': ({Color? seed}) => ${theme.builderName}(seed: seed),",
      )
      .join('\n');
  return '''// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/theme_catalog.dart.
$imports
class ThemeRegistry {
  const ThemeRegistry._();

  static const defaultThemeName = 'default';
  static const fallbackThemeName = 'fallback';

  static final Map<String, ThemeBuilder> _builders = <String, ThemeBuilder>{
$builders
  };

  static ThemeDefinition resolve(String name, {Color? seed}) {
    assert(
      _builders.containsKey(name),
      'Unknown MOZAIS_THEME "\$name"; falling back to \$fallbackThemeName.',
    );
    final builder = _builders[name] ?? _builders[fallbackThemeName]!;
    return builder(seed: seed);
  }
}
''';
}

String _withGeneratedDependencies(
  String pubspec,
  List<ThemePackage> themes,
  Directory catalogDirectory,
) {
  final start = pubspec.indexOf(generatedDependenciesStart);
  final end = pubspec.indexOf(
    generatedDependenciesEnd,
    start < 0 ? 0 : start + generatedDependenciesStart.length,
  );
  if (start < 0 || end < 0) {
    throw StateError(
      'Theme catalog pubspec is missing generated dependency markers.',
    );
  }

  final block = StringBuffer()..writeln(generatedDependenciesStart);
  for (final theme in themes) {
    block
      ..writeln('  ${theme.packageName}:')
      ..writeln(
        '    path: ${jsonEncode(path.relative(theme.directory.path, from: catalogDirectory.path))}',
      );
  }
  block.write('  $generatedDependenciesEnd');
  return pubspec.replaceRange(
    start,
    end + generatedDependenciesEnd.length,
    block.toString(),
  );
}

String _builderName(String themeName) {
  final words = themeName.split('_');
  final pascalName = words
      .map((word) => '${word[0].toUpperCase()}${word.substring(1)}')
      .join();
  return 'build${pascalName}Theme';
}

String _join(String base, String relative) {
  return '$base${Platform.pathSeparator}${relative.replaceAll('/', Platform.pathSeparator)}';
}
