// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/theme_catalog.dart.
import 'package:flutter/material.dart';
import 'package:theme_sdk/theme_sdk.dart';
import 'package:theme_default/theme.dart' show buildDefaultTheme;
import 'package:theme_fallback/theme.dart' show buildFallbackTheme;

class ThemeRegistry {
  const ThemeRegistry._();

  static const defaultThemeName = 'default';
  static const fallbackThemeName = 'fallback';

  static final Map<String, ThemeBuilder> _builders = <String, ThemeBuilder>{
    'default': ({Color? seed}) => buildDefaultTheme(seed: seed),
    'fallback': ({Color? seed}) => buildFallbackTheme(seed: seed),
  };

  static ThemeDefinition resolve(String name, {Color? seed}) {
    assert(
      _builders.containsKey(name),
      'Unknown MOZAIS_THEME "$name"; falling back to $fallbackThemeName.',
    );
    final builder = _builders[name] ?? _builders[fallbackThemeName]!;
    return builder(seed: seed);
  }
}
