name: theme_default
description: Built-in default theme for the Akari greeter.
publish_to: none

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  scene:
    path: ../../packages/scene
  greeter_components:
    path: ../../packages/greeter_components
  theme_sdk:
    path: ../../packages/theme_sdk

dev_dependencies:
  greeter:
    path: ../..
  yaml: ^3.1.3
  integration_test:
    sdk: flutter
  dbus: ^0.7.11
  greeter_ui:
    path: ../../packages/greeter_ui
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  scene_codegen:
    path: ../../packages/scene_codegen

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Light.otf
          weight: 300
        - asset: assets/fonts/SpaceGrotesk-Regular.otf
          weight: 400
        - asset: assets/fonts/SpaceGrotesk-Medium.otf
          weight: 500

perf:
  version: 1
  verify: [dart, run, perf/run.dart, verify]
  trace: [dart, run, perf/run.dart, trace]
